{
  try {
    return computable.compute();
  }
 catch (  IOException e) {
    myFatalErrorsConsumer.consume(e);
  }
  return null;
}
