{
  try {
    clientManager.getExceptionHandler().exceptionCaught(cause);
  }
  finally {
    super.exceptionCaught(context,cause);
  }
}
