{
  try {
    clientManager.getExceptionHandler().exceptionCaught(cause);
  }
  finally {
    context.channel().close();
  }
}
