{
  try {
    doTest();
    fail("Conflict expected.");
  }
 catch (  BaseRefactoringProcessor.ConflictsInTestsException e) {
    assertEquals("Method is used in method reference expression",e.getMessage());
  }
}
