{
  try {
    return cache.get(key);
  }
 catch (  ExecutionException e) {
    final Throwable cause=e.getCause();
    throw (cause instanceof IOException ? (IOException)cause : new IOException("Unexpected non-IO error",cause));
  }
}
