{
  try {
    doTest("foo1");
  }
 catch (  BaseRefactoringProcessor.ConflictsInTestsException e) {
    Assert.assertEquals("Method with same erasure is already defined in the class <b><code>RenameTest</code></b>",e.getMessage());
    return;
  }
  fail("Conflicts were not found");
}
