{
  final Throwable cause=exception.getCause();
  if (cause instanceof VagrantNotStartedException) {
    final String vagrantFolder=((VagrantNotStartedException)cause).getVagrantFolder();
    return new PyExecutionException("Vagrant instance is down",command,args,"","",0,ImmutableList.of(new LaunchVagrantFix(vagrantFolder)));
  }
  return exception;
}
