{
  try {
    myResult=fetch(indicator);
  }
 catch (  Exception e) {
    LOG.error(e);
    myException=e;
  }
}
