{
  assertOptions("try {\n" + "} catch(Exception e) {\n" + "    <caret>\n"+ "}\n","Unwrap 'try...'");
}
