{
  try {
    PullUpPresenter sut=configureByClass(className);
    mocksControl.replay();
    sut.launch();
  }
 catch (  IllegalArgumentException ignored) {
    return;
  }
  Assert.fail("Presenter should throw exception, but it returned list of parents instead: " + parentsCapture.getValue());
}
