{
  if (!future.isSuccess()) {
    Throwable cause=future.cause();
    if (cause == null) {
      setError("No success");
    }
 else {
      setError(cause);
    }
  }
}
