{
  try {
    server.exceptionHandler.exceptionCaught(cause);
  }
  finally {
    context.channel().close();
  }
}
